name: Test PowerShell Script
on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: PowerShell.exe -ExecutionPolicy UnRestricted -File .\setup.ps1
